name: Run Python Script

on:
  push:
    branches: [ "main" ]  # Запускать, когда ты сохраняешь файлы

jobs:
  build:
    runs-on: ubuntu-latest # Робот возьмет компьютер на системе Linux

    steps:
    - uses: actions/checkout@v3 # Робот копирует твой код к себе

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Устанавливает Python

    - name: Run my script
      run: python hello.py # Самая главная команда — запуск!
